config/routes.rb
Rails.application.routes.draw do

  resources :orders
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'products/:id/crop' => 'products#crop', as: :crop

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :providers
  resources :products
  resources :purchases

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :purchases
	before_save { self.email = email.downcase if self.email }

	validates :name,  presence: true, length: { maximum: 50 },
										uniqueness: true
	validates :tax_name, allow_blank: true, length: { maximum: 100 },
											 uniqueness: true
	validates :tax_id, allow_blank: true, length: { maximum: 30 },
										 uniqueness: true
	validates :address1, allow_blank: true, length: { maximum: 50 }
	validates :address2, allow_blank: true, length: { maximum: 50 }
	validates :city, allow_blank: true, length: { maximum: 50 }
	validates :state, allow_blank: true, length: { maximum: 50 }
	validates :zip, allow_blank: true, length: { maximum: 5 }
	validates :country, allow_blank: true, length: { maximum: 50 }
	validates :contact, allow_blank: true, uniqueness: true, length: { maximum: 50 }
	validates :mobile, allow_blank: true, uniqueness: true, length: { maximum: 30 }
	validates :phone, allow_blank: true, uniqueness: true, length: { maximum: 30 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, allow_blank: true, length: { maximum: 255 },
  									format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :webpage, allow_blank: true, length: { maximum: 255 },
  										uniqueness: true
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :admin_user,     only: [:edit, :update, :destroy]

	def index
    @providers = Provider.paginate(page: params[:page])
  end

  def show
  	@provider = Provider.find(params[:id])
  end

  def new
  	@provider = Provider.new
  end

  def create
    @provider = Provider.new(provider_params)    # Not the final implementation!
    if @provider.save
    	flash[:success] = "Proveedor Creado."
      redirect_to @provider
    else
      render 'new'
    end
  end

  def edit
    @provider = Provider.find(params[:id])
  end

  def update
    @provider = Provider.find(params[:id])
    if @provider.update_attributes(provider_params)
      flash[:success] = "Proveedor Actualizado."
      redirect_to @provider
    else
      render 'edit'
    end
  end

  def destroy
    Provider.find(params[:id]).destroy
    flash[:success] = "Proveedor Eliminado."
    redirect_to providers_url
  end

  private

    def provider_params
      params.require(:provider).permit(:name, :tax_name, :tax_id, :address1,
                                   		 :address2, :city, :state, :zip,
                                   		 :country, :contact, :mobile, :phone,
                                   		 :email, :webpage)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_fields.html.erb
<% @subject = @provider %>
<%= render 'shared/error_messages' %>

<div class="col-md-6">
  <%= f.label :name, "Nombre" %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :tax_name, "Razon Social" %>
  <%= f.text_field :tax_name, class: 'form-control' %>

  <%= f.label :tax_id, "RFC" %>
  <%= f.text_field :tax_id, class: 'form-control' %>

  <%= f.label :address1, "Calle" %>
  <%= f.text_field :address1, class: 'form-control' %>

  <%= f.label :address2, "Colonia" %>
  <%= f.text_field :address2, class: 'form-control' %>

  <%= f.label :city, "Ciudad" %>
  <%= f.text_field :city, class: 'form-control' %>

  <%= f.label :state, "Estado" %>
  <%= f.text_field :state, class: 'form-control' %>
</div>

<div class="col-md-6">
  <%= f.label :zip, "Codigo Postal" %>
  <%= f.text_field :zip, class: 'form-control' %>

  <%= f.label :country, "Pais" %>
  <%= f.text_field :country, class: 'form-control' %>

  <%= f.label :constct, "Contacto" %>
  <%= f.text_field :contact, class: 'form-control' %>

  <%= f.label :mobile, "Celular" %>
  <%= f.text_field :mobile, class: 'form-control' %>

  <%= f.label :phone, "Telefono" %>
  <%= f.text_field :phone, class: 'form-control' %>

  <%= f.label :email, "Correo Electronico" %>
  <%= f.text_field :email, class: 'form-control' %>

  <%= f.label :webpage, "Pagina de Interet" %>
  <%= f.text_field :webpage, class: 'form-control' %>
</div>

app/views/providers/_provider.html.erb
<li>
  <%= link_to provider.name, provider %>
  <% if current_user.admin? %>
  	| <%= link_to "editar", edit_provider_path(provider) %>
    | <%= link_to "eliminar", provider, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/providers/edit.html.erb
<% provide(:title, 'Editar Proveedor') %>
<h1>Actualizar datos del Proveedor</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@provider) do |f| %>
      <%= render 'fields', f: f %>
      <div class="col-md-6 col-md-offset-3">
        <%= f.submit "Modificar Proveedor", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/providers/index.html.erb
<% provide(:title, 'Proveedores') %>
<h1>Proveedores <small>
	<%= link_to "nuevo", new_provider_path %>
</small></h1>

<%= will_paginate %>

<ul class="providers">
  <% @providers.each do |provider| %>
    <%= render provider %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/providers/new.html.erb
<% provide(:title, 'Nuevo Proveedor') %>
<h1>Nuevo Proveedor</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@provider) do |f| %>
    	<%= render 'fields', f: f %>
      <div class="col-md-6 col-md-offset-3">
      <%= f.submit "Registrar Proveedor", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/providers/show.html.erb
<% provide(:title, @provider.name) %>
<h1><%= @provider.name %></h1>
<p>
	<%= @provider.address1 %><br>
	<%= @provider.address2 %><br>
	<%= @provider.city %><br>
	<%= @provider.state %><br>
	<%= @provider.zip %><br>
	<%= @provider.country %>
</p>