config/routes.rb
Rails.application.routes.draw do

  resources :orders
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'products/:id/crop' => 'products#crop', as: :crop

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :providers
  resources :products
  resources :purchases

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_reader :margin, :percent
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  has_many :purchase_detail
  has_many :purchases, through: :purchase_detail
  has_many :order_detail
  has_many :orders, through: :order_detail
  has_many :providers, through: :purchases

  mount_uploader :picture, PictureUploader

  after_create :enqueue_picture
  after_update :crop_picture

	validates :code, length: { maximum: 40 }, uniqueness: true
	validates :name,  presence: true, length: { maximum: 100 },
										uniqueness: {scope: :size}
	validates :description,  presence: true, length: { maximum: 255 }
	validates :size,  presence: true, length: { maximum: 20 },
										uniqueness: {scope: :name}
	validates :brand, length: { maximum: 100 }
	validates :model, allow_blank: true, length: { maximum: 100 }, uniqueness: true
	validates :line, length: { maximum: 100 }
  validate  :picture_size

  def margin
    self.price - self.cost if self.price && self.cost
  end

  def percent
    self.margin / self.price if self.margin
  end


  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

    def crop_picture
      if self.crop_x.present?
        self.picture.crop
        self.picture.resize_to_limit(1024, 1024)
        # picture.filename =~ /\/([^\/]*\.[^\.]*)[\?$]/
        # self.key = $1
        self.crop_x = nil
        self.picture.recreate_versions!
        self.remote_picture_url = picture.direct_fog_url(with_path: true)
        self.save!
        # enqueue_picture
      end
    end

    def enqueue_picture
      # PictureWorker.perform_async(id, key) unless key.index("filename")
      unless key.index("filename")
        self.key = key
        self.remote_picture_url = picture.direct_fog_url(with_path: true)
        self.save!
      end
    end

    class PictureWorker
      include Sidekiq::Worker

      def perform(id, key)
        product = Product.find id
        product.key = key
        product.remote_picture_url = product.picture.direct_fog_url(with_path: true)
        product.save!
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :admin_user,     only: [:edit, :destroy]

  def index
    #@products = Product.paginate(page: params[:page])
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new(key: params[:key])
    @uploader = @product.picture
    @uploader.success_action_redirect = new_product_url
  end

  def create
    @product = Product.new(product_params)    # Not the final implementation!
    if @product.save
      unless product_params[:key].index("filename")
        redirect_to crop_url id: @product.id
      else
        flash[:success] = "Producto Creado."
        redirect_to @product
      end
    else
      render 'new'
    end
  end

  def crop
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      if params[:product][:picture].present?
        render :crop
      else
        flash[:success] = "Producto Actualizado."
        redirect_to @product
      end
    else
      render 'edit'
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Producto Eliminado."
    redirect_to products_url
  end


  private

    def product_params
      params.require(:product).permit(:key, :code, :name, :description, :size,
                                      :brand, :model, :line, :picture,
                                      :crop_x, :crop_y, :crop_w, :crop_h)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_fields.html.erb
<% @subject = @product %>
<%= render 'shared/error_messages' %>

<%= f.label :code %>
<%= f.text_field :code, class: 'form-control' %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :description %>
<%= f.text_field :description, class: 'form-control' %>

<%= f.label :size %>
<%= f.text_field :size, class: 'form-control' %>

<%= f.label :brand %>
<%= f.text_field :brand, class: 'form-control' %>

<%= f.label :model %>
<%= f.text_field :model, class: 'form-control' %>

<%= f.label :line %>
<%= f.text_field :line, class: 'form-control' %>

app/views/products/_product.html.erb
<tr>
  <td><%= image_tag product.picture.url(:thumb), alt: "image" if product.picture.url %></td>
  <td><%= link_to product.code, product %></td>
  <td><%= product.description %></td>
  <td><%= product.inventory%></td>
  <td><%= number_to_currency product.price %></td>
  <% if current_user.admin? %>
  	<td><%= link_to "editar", edit_product_path(product) %></td>
    <td><%= link_to "eliminar", product, method: :delete,
                                  data: { confirm: "You sure?" } %></td>
  <% end %>
</tr>

app/views/products/crop.html.erb
<h1>Recortar Foto</h1>

<%= image_tag @product.picture_url(:large), id: "cropbox" %>

<h4>Preview</h4>
<div style="width:102px; height:102px; border:1px solid black">
<div style="width:100px; height:100px; overflow:hidden" id="preview_port">
  <%= image_tag @product.picture.url(:large), id: "preview" %>
</div>
</div>

<%= form_for @product do |f| %>
  <div class="actions">
    <% %w[x y w h].each do |attribute| %>
      <%= f.hidden_field "crop_#{attribute}" %>
    <% end %>
    <%= f.submit "Crop" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% provide(:title, 'Editar Producto') %>
<h1>Actualizar datos del Producto</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@product) do |f| %>
      <%= render 'fields', f: f %>
      <div class="col-md-6 col-md-offset-3">
        <%= f.submit "Modificar Proveedor", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<% provide(:title, 'Productos') %>
<h1>Productos <small>
	<%= link_to "nuevo", new_product_path %>
</small></h1>

<table id="products">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Codigo</th>
      <th>Descripcion</th>
      <th>Inventario</th>
      <th>Precio</th>
      <% if current_user.admin? %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <%= render product %>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<% provide(:title, 'Nuevo Producto') %>
<h1>Nuevo Producto</h1>

<div class="row">
  <div class="col-md-12">

    <% if @product.key.index("filename") %>
      <%= direct_upload_form_for @uploader do |f| %>
        <p><%= f.file_field :picture %></p>
        <p><%= f.submit "Upload Picture" %></p>
      <% end %>
    <% else %>
      <p>Picture succesfully uploaded!</p>
    <% end %>

    <%= form_for(@product, html: { multipart: true }) do |f| %>
      <%= f.hidden_field :key %>
    	<%= render 'fields', f: f %>
      <div class="col-md-6 col-md-offset-3">
      <%= f.submit "Registrar Producto", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>
<h1><%= @product.name %></h1>
<p>
	<%= @product.code %><br>
	<%= @product.name %><br>
	<%= @product.description %><br>
	<%= @product.size %><br>
	<%= @product.brand %><br>
	<%= @product.model %><br>
	<%= @product.line %><br>
  <%= image_tag @product.picture.url(:medium) if @product.picture? %>
</p>