config/routes.rb
Rails.application.routes.draw do

  resources :orders
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'products/:id/crop' => 'products#crop', as: :crop

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :providers
  resources :products
  resources :purchases

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.facebook.com/efiguerc/">Huellitas Web App</a>
    by <a href="mailto:efiguerc@gmail.com">Edgar Figueroa</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "huellitas web app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if logged_in? %>
          <li><%= link_to "Ventas",   '#' %></li>
          <li><%= link_to "Pedidos",   orders_path %></li>
          <li><%= link_to "Compras",   purchases_path %></li>
          <li><%= link_to "Productos",   products_path %></li>
          <li><%= link_to "Proveedores",   providers_path %></li>
          <li><%= link_to "Usuarios", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Ajustes", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Ayuda",   help_path %></li>
              <li><%= link_to "Salir", logout_path, method: "delete" %></li>

            </ul>
          </li>
        <% else %>
          <li><%= link_to "Ayuda",   help_path %></li>
          <li><%= link_to "Entrar", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
    <title><%= full_title(yield(:title)) %></title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
	</head>
	<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
	</body>
</html>